//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.33440
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Approval.Web.ApprovalWorkflowService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ApprovalWorkflowService.IService")]
    public interface IService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/BeginApprovalProcess", ReplyAction="http://tempuri.org/IService/BeginApprovalProcessResponse")]
        void BeginApprovalProcess(string[] approverEmails, string messageToApprove, string yourEmail);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/BeginApprovalProcess", ReplyAction="http://tempuri.org/IService/BeginApprovalProcessResponse")]
        System.Threading.Tasks.Task BeginApprovalProcessAsync(string[] approverEmails, string messageToApprove, string yourEmail);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/Approve", ReplyAction="http://tempuri.org/IService/ApproveResponse")]
        void Approve(string approverId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/Approve", ReplyAction="http://tempuri.org/IService/ApproveResponse")]
        System.Threading.Tasks.Task ApproveAsync(string approverId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/Decline", ReplyAction="http://tempuri.org/IService/DeclineResponse")]
        void Decline(string approverId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/Decline", ReplyAction="http://tempuri.org/IService/DeclineResponse")]
        System.Threading.Tasks.Task DeclineAsync(string approverId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceChannel : Approval.Web.ApprovalWorkflowService.IService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceClient : System.ServiceModel.ClientBase<Approval.Web.ApprovalWorkflowService.IService>, Approval.Web.ApprovalWorkflowService.IService {
        
        public ServiceClient() {
        }
        
        public ServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void BeginApprovalProcess(string[] approverEmails, string messageToApprove, string yourEmail) {
            base.Channel.BeginApprovalProcess(approverEmails, messageToApprove, yourEmail);
        }
        
        public System.Threading.Tasks.Task BeginApprovalProcessAsync(string[] approverEmails, string messageToApprove, string yourEmail) {
            return base.Channel.BeginApprovalProcessAsync(approverEmails, messageToApprove, yourEmail);
        }
        
        public void Approve(string approverId) {
            base.Channel.Approve(approverId);
        }
        
        public System.Threading.Tasks.Task ApproveAsync(string approverId) {
            return base.Channel.ApproveAsync(approverId);
        }
        
        public void Decline(string approverId) {
            base.Channel.Decline(approverId);
        }
        
        public System.Threading.Tasks.Task DeclineAsync(string approverId) {
            return base.Channel.DeclineAsync(approverId);
        }
    }
}
